hmrc/emcs-tfe-create-movement-frontend

app/controllers/sections/journeyType/GiveInformationOtherTransportController.scala
app/forms/package.scala
app/forms/sections/journeyType/GiveInformationOtherTransportFormProvider.scala
app/models/sections/journeyType/HowMovementTransported.scala
app/navigation/JourneyTypeNavigator.scala
app/pages/ConsignorAddressPage.scala
app/pages/sections/journeyType/GiveInformationOtherTransportPage.scala
app/viewmodels/sections/journeyType/checkAnswers/GiveInformationOtherTransportSummary.scala
app/views/sections/journeyType/GiveInformationOtherTransportView.scala.html
conf/app.routes
conf/messages.cy
conf/messages.en
test-utils/fixtures/messages/sections/journeyType/GiveInformationOtherTransportMessages.scala
test/controllers/sections/journeyType/GiveInformationOtherTransportControllerSpec.scala
test/forms/sections/journeyType/GiveInformationOtherTransportFormProviderSpec.scala
test/navigation/JourneyTypeNavigatorSpec.scala
test/pages/sections/journeyType/GiveInformationOtherTransportPageSpec.scala
test/viewmodels/sections/journeyType/checkAnswers/GiveInformationOtherTransportSummarySpec.scala
test/views/sections/journeyType/GiveInformationOtherTransportViewSpec.scala

built on top of https://github.com/hmrc/emcs-tfe-create-movement-frontend/pull/20 so that ideally needs merging 1st and then this branch can then be rebased and put up for review

ETFE-1933 CAM-JT02:give-information-other-transport

---

.g8/datePage/app/views/$className$View.scala.html
app/forms/mappings/LocalDateFormatter.scala
app/viewmodels/govuk/DateFluency.scala
test/forms/mappings/DateMappingsSpec.scala

Includes fixes for ETFE-2003 and ETFE-2005

[ETFE-2002] Acccessibility fixes for Date page

---

app/controllers/sections/destination/DestinationAddressController.scala
app/navigation/DestinationNavigator.scala
app/pages/sections/destination/DestinationAddressPage.scala
conf/app.routes
conf/destination.routes
conf/dispatch.routes
conf/messages.cy
conf/messages.en
test-utils/fixtures/messages/AddressMessages.scala
test/controllers/sections/destination/DestinationAddressControllerSpec.scala
test/navigation/DestinationNavigatorSpec.scala
test/navigation/FakeNavigators.scala
test/views/AddressViewSpec.scala

ETFE-2168 added the destination Address

---

app/config/AppConfig.scala
app/controllers/sections/exportInformation/ExportCustomsOfficeController.scala
app/forms/mappings/Constraints.scala
app/forms/sections/exportInformation/ExportCustomsOfficeFormProvider.scala
app/models/sections/info/DestinationType.scala
app/navigation/ExportInformationNavigator.scala
app/pages/sections/exportInformation/ExportCustomsOfficePage.scala
app/viewmodels/checkAnswers/sections/exportInformation/ExportCustomsOfficeSummary.scala
app/views/sections/exportInformation/ExportCustomsOfficeView.scala.html
conf/app.routes
conf/exportInformation.routes
conf/messages.cy
conf/messages.en
test-utils/fixtures/messages/BaseMessages.scala
test-utils/fixtures/messages/sections/exportInformation/ExportCustomsOfficeMessages.scala
test/controllers/sections/exportInformation/ExportCustomsOfficeControllerSpec.scala
test/forms/sections/exportInformation/ExportCustomsOfficeFormProviderSpec.scala
test/navigation/ExportInformationNavigatorSpec.scala
test/navigation/FakeNavigators.scala
test/views/sections/exportInformation/ExportCustomsOfficeViewSpec.scala

Note, viewmodel will be tested as part of the CheckAnswers story next.

[ETFE-2156] Added the ExportCustomsOfficeCode view

---

app/controllers/sections/transportUnit/TransportUnitIdentityController.scala
app/forms/sections/transportUnit/TransportUnitIdentityFormProvider.scala
app/navigation/TransportUnitNavigator.scala
app/pages/sections/transportUnit/TransportUnitIdentityPage.scala
app/viewmodels/checkAnswers/sections/transportUnit/TransportUnitIdentitySummary.scala
app/viewmodels/checkAnswers/sections/transportUnit/TransportUnitTypeSummary.scala
app/views/sections/transportUnit/TransportUnitIdentityView.scala.html
conf/messages.cy
conf/messages.en
conf/transportUnit.routes
test-utils/fixtures/messages/sections/transportUnit/TransportUnitIdentityMessages.scala
test-utils/fixtures/messages/sections/transportUnit/TransportUnitTypeMessages.scala
test/controllers/sections/transportUnit/TransportUnitIdentityControllerSpec.scala
test/forms/sections/transportUnit/TransportUnitIdentityFormProviderSpec.scala
test/navigation/TransportUnitNavigatorSpec.scala
test/viewmodels/checkAnswers/sections/transportUnit/TransportUnitIdentitySummarySpec.scala
test/viewmodels/checkAnswers/sections/transportUnit/TransportUnitTypeSummarySpec.scala
test/views/sections/transportUnit/TransportUnitIdentityViewSpec.scala

* Added transport unit summary row
* One question outstanding with the autocomplete (on/off)
* Decision is to set the auto complete to on

[ETFE-2177] added transport units identity page

---

app/controllers/sections/guarantor/GuarantorAddressController.scala
app/controllers/sections/guarantor/GuarantorArrangerController.scala
app/navigation/GuarantorNavigator.scala
app/pages/sections/guarantor/GuarantorAddressPage.scala
conf/application.conf
conf/guarantor.routes
conf/messages.cy
conf/messages.en
test-utils/fixtures/messages/AddressMessages.scala
test/controllers/sections/guarantor/GuarantorAddressControllerSpec.scala
test/controllers/sections/guarantor/GuarantorArrangerControllerSpec.scala
test/navigation/GuarantorNavigatorSpec.scala
test/views/AddressViewSpec.scala

Dependant on https://github.com/hmrc/emcs-tfe-create-movement-frontend/pull/84

ETFE-2205 CAM-G05 guarantor-address

---

app/controllers/sections/journeyType/JourneyTimeHoursController.scala
app/forms/sections/journeyType/JourneyTimeHoursFormProvider.scala
app/navigation/JourneyTypeNavigator.scala
app/pages/sections/journeyType/JourneyTimeHoursPage.scala
app/viewmodels/checkAnswers/sections/journeyType/JourneyTimeHoursSummary.scala
app/viewmodels/helpers/CheckYourAnswersJourneyTypeHelper.scala
app/views/sections/journeyType/JourneyTimeHoursView.scala.html
conf/journeyType.routes
conf/messages.cy
conf/messages.en
test-utils/fixtures/messages/sections/journeyType/JourneyTimeHoursMessages.scala
test/controllers/sections/journeyType/JourneyTimeHoursControllerSpec.scala
test/forms/mappings/MappingsSpec.scala
test/forms/sections/journeyType/JourneyTimeHoursFormProviderSpec.scala
test/viewmodels/checkAnswers/sections/journeyType/JourneyTimeHoursSummarySpec.scala
test/views/sections/journeyType/JourneyTimeHoursViewSpec.scala

TODO's added to delete the answer and route to CAM-JT03 when CAM-JT03 is addressed
Content alignment is needed for the error message when 0 (zero) or a negative number is entered

[ETFE-2292] - Added journey time hours page (CAM-JT04)

---

app/views/sections/journeyType/JourneyTimeHoursView.scala.html

HTML extract:
View (unchanged):

[ETFE-2379] - Fixed a11y issue on journey time hours page

---

app/controllers/sections/dispatch/DispatchIndexController.scala
app/controllers/sections/dispatch/DispatchWarehouseExciseController.scala
app/forms/sections/dispatch/DispatchWarehouseExciseFormProvider.scala
app/navigation/DispatchNavigator.scala
app/pages/sections/dispatch/DispatchWarehouseExcisePage.scala
app/repositories/SessionRepository.scala
app/viewmodels/checkAnswers/sections/dispatch/DispatchWarehouseExciseSummary.scala
app/views/sections/dispatch/DispatchWarehouseExciseView.scala.html
app/views/sections/transportUnit/TransportUnitGiveMoreInformationChoiceView.scala.html
app/views/sections/transportUnit/TransportUnitGiveMoreInformationView.scala.html
conf/dispatch.routes
conf/messages.cy
conf/messages.en
test-utils/fixtures/messages/sections/dispatch/DispatchWarehouseExciseMessages.scala
test/controllers/sections/dispatch/DispatchIndexControllerSpec.scala
test/controllers/sections/dispatch/DispatchWarehouseExciseControllerSpec.scala
test/forms/behaviours/FieldBehaviours.scala
test/forms/sections/dispatch/DispatchWarehouseExciseFormProviderSpec.scala
test/forms/sections/exportInformation/ExportCustomsOfficeFormProviderSpec.scala
test/forms/sections/importInformation/ImportCustomsOfficeCodeFormProviderSpec.scala
test/navigation/DispatchNavigatorSpec.scala
test/viewmodels/checkAnswers/sections/dispatch/DispatchCheckAnswersHelperSpec.scala
test/viewmodels/checkAnswers/sections/dispatch/DispatchWarehouseExciseSummarySpec.scala
test/views/sections/dispatch/DispatchWarehouseExciseViewSpec.scala

Updated index controller to point to this page
Hint text and error messages were changed (see V06 of copydeck)

[ETFE-2375] - Add dispatch warehouse excise page (CAM-DIS01)

---

app/controllers/sections/info/InformationCheckAnswersController.scala
app/viewmodels/checkAnswers/sections/info/InformationCheckAnswersHelper.scala
app/viewmodels/checkAnswers/sections/info/InformationLocalReferenceNumberSummary.scala
conf/messages
test-utils/fixtures/messages/sections/info/LocalReferenceNumberMessages.scala
test/controllers/sections/info/InformationCheckAnswersControllerSpec.scala
test/mocks/viewmodels/MockInformationCheckAnswersHelper.scala
test/viewmodels/checkAnswers/sections/info/InformationLocalReferenceNumberSummarySpec.scala

ETFE-2390 Bug fix

---

app/controllers/sections/journeyType/HowMovementTransportedController.scala
app/pages/sections/journeyType/JourneyTypeSection.scala
app/viewmodels/checkAnswers/sections/journeyType/GiveInformationOtherTransportSummary.scala
app/viewmodels/checkAnswers/sections/journeyType/HowMovementTransportedSummary.scala
app/viewmodels/helpers/CheckYourAnswersJourneyTypeHelper.scala
app/views/sections/info/DestinationTypeView.scala.html
app/views/sections/journeyType/GiveInformationOtherTransportView.scala.html
app/views/sections/journeyType/HowMovementTransportedView.scala.html
test/controllers/sections/journeyType/HowMovementTransportedControllerSpec.scala
test/pages/sections/journeyType/JourneyTypeSectionSpec.scala
test/viewmodels/checkAnswers/sections/journeyType/GiveInformationOtherTransportSummarySpec.scala
test/viewmodels/checkAnswers/sections/journeyType/HowMovementTransportedSummarySpec.scala
test/viewmodels/checkAnswers/sections/journeyType/JourneyTypeCheckAnswersHelperSpec.scala
test/views/sections/journeyType/GiveInformationOtherTransportViewSpec.scala
test/views/sections/journeyType/HowMovementTransportedViewSpec.scala

Etfe 2289 - added 2 pages to the journey type check you answers

---

app/controllers/sections/documents/BaseDocumentsNavigationController.scala
app/controllers/sections/documents/DocumentsRemoveFromListController.scala
app/controllers/sections/journeyType/HowMovementTransportedController.scala
app/forms/sections/documents/DocumentsRemoveFromListFormProvider.scala
app/models/requests/DataRequest.scala
app/pages/sections/documents/DocumentsSectionIndex.scala
app/queries/DocumentsCount.scala
app/views/sections/documents/DocumentsRemoveFromListView.scala.html
conf/documents.routes
conf/messages
test-utils/fixtures/messages/BaseMessages.scala
test-utils/fixtures/messages/sections/documents/DocumentsRemoveFromListMessages.scala
test/controllers/sections/documents/DocumentsRemoveFromListControllerSpec.scala
test/forms/sections/documents/DocumentsRemoveFromListFormProviderSpec.scala
test/views/sections/documents/DocumentsRemoveFromListViewSpec.scala

There's some TODOs which will be completed as part of Ladon's PR for ETFE-2479

[ETFE-2482] Added the Documents Remove from List view

---

app/connectors/referenceData/GetDocumentTypesConnector.scala
app/forms/sections/documents/DocumentTypeFormProvider.scala
app/forms/sections/transportUnit/TransportUnitIdentityFormProvider.scala
app/pages/sections/documents/DocumentTypePage.scala
test/controllers/sections/documents/DocumentTypeControllerSpec.scala
test/forms/sections/transportUnit/TransportUnitIdentityFormProviderSpec.scala

Error message will be changed as part of a future story

[ETFE-2570] - Allow spaces on CAM-TU02

---

app/controllers/sections/items/ItemFiscalMarksChoiceController.scala
app/forms/sections/items/ItemFiscalMarksChoiceFormProvider.scala
app/models/ExciseProductCode.scala
app/models/SelectOptionModel.scala
app/navigation/ItemsNavigator.scala
app/pages/sections/items/ItemFiscalMarksChoicePage.scala
app/viewmodels/checkAnswers/sections/items/ItemFiscalMarksChoiceSummary.scala
app/viewmodels/helpers/SelectItemHelper.scala
app/views/sections/items/ItemFiscalMarksChoiceView.scala.html
conf/items.routes
conf/messages
test-utils/fixtures/messages/sections/items/ItemFiscalMarksChoiceMessages.scala
test/controllers/sections/items/ItemFiscalMarksChoiceControllerSpec.scala
test/controllers/sections/items/ItemGeographicalIndicationChoiceControllerSpec.scala
test/forms/sections/items/ItemFiscalMarksChoiceFormProviderSpec.scala
test/navigation/ItemsNavigatorSpec.scala
test/viewmodels/checkAnswers/sections/items/ItemFiscalMarksChoiceSummarySpec.scala
test/views/sections/items/ItemFiscalMarksChoiceViewSpec.scala
test/views/sections/transportUnit/TransportUnitGiveMoreInformationChoiceViewSpec.scala

Renamed the SelectOption due to library class name conflict
Added yes/no view tests for TU05

[ETFE-2611] - Add fiscal-marks-choice page (CAM-ITM22)

---

app/viewmodels/helpers/DocumentsAddToListHelper.scala
app/views/components/span.scala.html
app/views/components/tag.scala.html
conf/messages
test-utils/fixtures/messages/sections/documents/DocumentsAddToListMessages.scala
test/viewmodels/helpers/DocumentsAddToListHelperSpec.scala
test/views/sections/documents/DocumentsAddToListViewSpec.scala

[ETFE-2479] added incomplete tag to DocumentAddToList page

---

app/config/Module.scala
app/connectors/referenceData/GetCountriesAndMemberStatesConnector.scala
app/connectors/referenceData/GetCountriesHttpParser.scala
app/models/response/ErrorResponse.scala
app/services/GetCountriesAndMemberStatesService.scala
it/connectors/GetCountriesAndMemberStatesConnectorISpec.scala
test-utils/fixtures/BaseFixtures.scala
test/connectors/referenceData/GetCountriesAndMemberStatesConnectorSpec.scala
test/connectors/referenceData/GetCountriesHttpParserSpec.scala
test/mocks/connectors/MockGetCountriesAndMemberStatesConnector.scala
test/mocks/services/MockGetCountriesAndMemberStatesService.scala
test/services/GetCountriesAndMemberStatesServiceSpec.scala

Reuses the member states parser as it maps to the same model

[ETFE-2733] - Add connector/service for countries + member states

---

app/controllers/sections/consignee/ConsigneeExemptOrganisationController.scala
app/controllers/sections/items/ItemWineOriginController.scala
app/forms/sections/items/ItemWineOriginFormProvider.scala
app/models/CountryModel.scala
app/navigation/ItemsNavigator.scala
app/pages/sections/items/ItemImportedWineChoicePage.scala
app/pages/sections/items/ItemWineOriginPage.scala
app/services/GetCountriesAndMemberStatesService.scala
app/services/GetMemberStatesService.scala
app/viewmodels/checkAnswers/sections/items/ItemWineOriginSummary.scala
app/views/sections/items/ItemWineOriginView.scala.html
conf/items.routes
conf/messages
test-utils/fixtures/BaseFixtures.scala
test-utils/fixtures/messages/sections/items/ItemWineOriginMessages.scala
test/controllers/sections/consignee/ConsigneeExemptOrganisationControllerSpec.scala
test/controllers/sections/items/ItemWineOriginControllerSpec.scala
test/forms/sections/items/ItemWineOriginFormProviderSpec.scala
test/mocks/services/MockGetCountriesAndMemberStatesService.scala
test/mocks/services/MockGetMemberStatesService.scala
test/navigation/ItemsNavigatorSpec.scala
test/services/GetCountriesAndMemberStatesServiceSpec.scala
test/services/GetMemberStatesServiceSpec.scala
test/viewmodels/checkAnswers/sections/items/ItemWineOriginSummarySpec.scala
test/views/sections/items/ItemWineOriginViewSpec.scala

Raising as draft until a few things are checked with UCD

[ETFE-2301] - Added wine origin (CAM-ITM16) page

---

app/controllers/sections/destination/DestinationBusinessNameController.scala
app/viewmodels/helpers/ItemsAddToListHelper.scala
test/viewmodels/helpers/ItemsAddToListHelperSpec.scala

[ETFE-2879] change item-add-to-list heading level to h2

---

app/models/submitCreateMovement/MovementGuaranteeModel.scala
app/models/submitCreateMovement/TraderModel.scala
test-utils/fixtures/ItemFixtures.scala
test/models/submitCreateMovement/MovementGuaranteeModelSpec.scala
test/models/submitCreateMovement/TraderModelSpec.scala

Mirroring what legacy does https://github.com/hmrc/emcs/blob/v3.284.0/emcs-backend/src/main/java/uk/gov/hmrc/portal/emcs/business/service/movement/draft/DefaultDraftMovementService.java#L585-L602

ETFE-2926 Remove Guarantor address when of a specific guarantor type

---

app/forms/package.scala
app/forms/sections/consignee/ConsigneeExciseFormProvider.scala
app/forms/sections/dispatch/DispatchWarehouseExciseFormProvider.scala
conf/messages
test-utils/fixtures/messages/sections/consignee/ConsigneeExciseMessages.scala
test/controllers/sections/dispatch/DispatchWarehouseExciseControllerSpec.scala
test/forms/behaviours/FieldBehaviours.scala
test/forms/behaviours/StringFieldBehaviours.scala
test/forms/sections/consignee/ConsigneeExciseFormProviderSpec.scala
test/forms/sections/dispatch/DispatchWarehouseExciseFormProviderSpec.scala

Need to discuss the 16 char validation but that can be raised as a separate PR

[ETFE-2905] - Add ERN validation on DispatchWarehouseExcise & ConsigneeExcise pages

---

app/controllers/sections/items/ItemWineProductCategoryController.scala
conf/messages
project/plugins.sbt
test-utils/fixtures/messages/sections/items/ItemPackagingProductTypeMessages.scala

[ETFE-2971] - Changed 'Contains one product type' to 'More than one item in the package'

---

app/assets/stylesheets/application.scss

[ETFE-StylisedPrint] - Added styling for stylised print

---

app/controllers/sections/consignee/ConsigneeExportVatController.scala
app/forms/sections/consignee/ConsigneeExportVatFormProvider.scala
app/navigation/ConsigneeNavigator.scala
app/pages/sections/consignee/ConsigneeExportVatPage.scala
app/viewmodels/checkAnswers/sections/consignee/ConsigneeExportVatSummary.scala
app/viewmodels/helpers/CheckYourAnswersConsigneeHelper.scala
app/views/sections/consignee/ConsigneeExportVatView.scala.html
conf/consignee.routes
conf/messages
test-utils/fixtures/BaseFixtures.scala
test-utils/fixtures/messages/sections/consignee/ConsigneeExportVatMessages.scala
test/controllers/sections/consignee/ConsigneeExportVatControllerSpec.scala
test/forms/sections/consignee/ConsigneeExportVatFormProviderSpec.scala
test/navigation/ConsigneeNavigatorSpec.scala
test/repository/SessionRepositorySpec.scala
test/viewmodels/checkAnswers/sections/consignee/ConsigneeExportVatSummarySpec.scala
test/viewmodels/helpers/CheckYourAnswersConsigneeHelperSpec.scala
test/views/sections/consignee/ConsigneeExportVatViewSpec.scala

Second version of the page after alignment
~Needs ETFE-3153 to go in first~

[ETFE-3147] - Added consignee export VAT page v2

---

app/views/sections/items/ItemDegreesPlatoView.scala.html
conf/messages
test-utils/fixtures/messages/CountryMessages.scala
test/views/sections/items/ItemDegreesPlatoViewSpec.scala

ETFE-3533 Remove Netherlands from degree-plato hard coded country list

---

app/connectors/emcsTfe/EmcsTfeHttpParser.scala
app/forms/sections/items/ItemSelectPackagingFormProvider.scala
app/models/audit/AuditModel.scala
app/models/audit/SubmitCreateMovementAudit.scala
app/models/response/ErrorResponse.scala
app/services/AuditingService.scala
app/services/SubmitCreateMovementService.scala
conf/application.conf
it/connectors/SubmitCreateMovementConnectorISpec.scala
test-utils/fixtures/BaseFixtures.scala
test/connectors/emcsTfe/EmcsTfeHttpParserSpec.scala
test/controllers/sections/items/ItemSelectPackagingControllerSpec.scala
test/forms/sections/items/ItemSelectPackagingFormProviderSpec.scala
test/mocks/services/MockAuditingService.scala
test/services/AuditServiceSpec.scala
test/services/SubmitCreateMovementServiceSpec.scala

Raising as draft whilst I check some more scenarios

[ETFE-3675] - Added CaM submission request/response audit event

---

app/controllers/sections/items/ItemPackagingQuantityController.scala
app/navigation/ItemsNavigator.scala
app/views/components/details.scala.html
app/views/sections/items/ItemPackagingQuantityView.scala.html
conf/messages
test-utils/fixtures/messages/sections/items/ItemPackagingQuantityMessages.scala
test/controllers/sections/items/ItemPackagingQuantityControllerSpec.scala
test/views/sections/items/ItemPackagingQuantityViewSpec.scala

Path checked - TODO added (currently goes to the correct place but the destination page is going to be refactored).

[ETFE-3728] - Added details link to the packaging quantity page

---

app/controllers/sections/items/ItemPackagingShippingMarksChoiceController.scala
app/viewmodels/helpers/ShippingMarksPackagingHelper.scala
app/views/sections/items/ItemPackagingShippingMarksChoiceView.scala.html
conf/messages
test-utils/fixtures/messages/sections/items/ItemPackagingShippingMarksChoiceMessages.scala
test/controllers/sections/items/ItemPackagingShippingMarksChoiceControllerSpec.scala
test/views/sections/items/ItemPackagingShippingMarksChoiceViewSpec.scala

**Note:**
- #303 should be reviewed and merged first, then this branch rebased from `main`

[ETFE-3790] Add dynamic text to CAM-ITM26 (shipping marks choice)

---

app/featureswitch/core/config/FeatureSwitchingModule.scala
app/pages/sections/items/ItemsSectionItem.scala

[ETFE-3952] - Add return to legacy feature to feature list so its on the feature switch page

---

app/controllers/sections/guarantor/GuarantorArrangerController.scala
app/models/sections/guarantor/GuarantorArranger.scala
app/views/sections/guarantor/GuarantorArrangerView.scala.html
test/controllers/sections/guarantor/GuarantorArrangerControllerSpec.scala
test/models/sections/guarantor/GuarantorArrangerSpec.scala
test/views/sections/guarantor/GuarantorArrangerViewSpec.scala

Related: https://github.com/hmrc/emcs-tfe-journey-tests/pull/479

[ETFE-3821] remove Consignee option on GuarantorArrangerView when MovementScenario doesn't allow a Consignee for this option

---

build.sbt

Originally done as part of #335

[ETFE-4070] set uglifyOps := UglifyOps.singleFile so we can use a more recent Node version

---

app/forms/sections/destination/DestinationWarehouseExciseFormProvider.scala
app/forms/sections/dispatch/DispatchWarehouseExciseFormProvider.scala
app/models/sections/info/DispatchPlace.scala
app/models/submitCreateMovement/SubmitCreateMovementModel.scala
app/views/sections/info/DispatchPlaceView.scala.html
conf/messages
test-utils/fixtures/ItemFixtures.scala
test-utils/fixtures/messages/sections/info/DispatchPlaceMessages.scala
test/controllers/sections/dispatch/DispatchWarehouseExciseControllerSpec.scala
test/forms/sections/dispatch/DispatchWarehouseExciseFormProviderSpec.scala
test/models/submitCreateMovement/SubmitCreateMovementModelSpec.scala
test/views/sections/info/DispatchPlaceViewSpec.scala

Also contains a content change on /info/dispatch-place to make the impact of that answer clearer.

[ETFE-4134] Improve validation on the Dispatch Place ERN form provider

---

app/viewmodels/checkAnswers/sections/transportUnit/TransportSealChoiceSummary.scala
app/viewmodels/checkAnswers/sections/transportUnit/TransportSealInformationSummary.scala
app/viewmodels/checkAnswers/sections/transportUnit/TransportSealTypeSummary.scala
app/viewmodels/checkAnswers/sections/transportUnit/TransportUnitGiveMoreInformationSummary.scala
app/viewmodels/checkAnswers/sections/transportUnit/TransportUnitIdentitySummary.scala
app/viewmodels/checkAnswers/sections/transportUnit/TransportUnitTypeSummary.scala
conf/messages
test-utils/fixtures/messages/sections/transportUnit/TransportSealChoiceMessages.scala
test-utils/fixtures/messages/sections/transportUnit/TransportSealTypeMessages.scala
test-utils/fixtures/messages/sections/transportUnit/TransportUnitGiveMoreInformationMessages.scala
test-utils/fixtures/messages/sections/transportUnit/TransportUnitIdentityMessages.scala
test-utils/fixtures/messages/sections/transportUnit/TransportUnitTypeMessages.scala
test/viewmodels/checkAnswers/sections/transportUnit/TransportSealChoiceSummarySpec.scala
test/viewmodels/checkAnswers/sections/transportUnit/TransportSealInformationSummarySpec.scala
test/viewmodels/checkAnswers/sections/transportUnit/TransportSealTypeSummarySpec.scala
test/viewmodels/checkAnswers/sections/transportUnit/TransportUnitGiveMoreInformationSummarySpec.scala
test/viewmodels/checkAnswers/sections/transportUnit/TransportUnitIdentitySummarySpec.scala
test/viewmodels/checkAnswers/sections/transportUnit/TransportUnitTypeSummarySpec.scala

[ETFE-4272] - Add index to change links for TU's

---

app/models/sections/guarantor/GuarantorArranger.scala
app/models/sections/info/movementScenario/MovementScenario.scala
app/models/sections/items/ExciseProductCodeRules.scala
app/pages/sections/guarantor/GuarantorRequiredPage.scala
app/views/components/clearAccessibleAutocompleteButton.scala.html
conf/messages
test-utils/fixtures/messages/sections/items/ItemExciseProductCodeMessages.scala
test/controllers/sections/items/ItemExciseProductCodeControllerSpec.scala
test/models/sections/guarantor/GuarantorArrangerSpec.scala
test/models/sections/items/ExciseProductCodeRulesSpec.scala

- Aligned the items rules to the latest copydeck
- Updated h1
- Hidden the "Clear" button when JS is disabled

[ETFE-3426] demo comments

---

app/config/Constants.scala
app/forms/sections/consignee/ConsigneeExciseFormProvider.scala
app/models/sections/info/movementScenario/MovementScenario.scala
app/pages/QuestionPage.scala
app/pages/sections/info/DestinationTypePage.scala
conf/messages
test-utils/fixtures/BaseFixtures.scala
test/forms/sections/consignee/ConsigneeExciseFormProviderSpec.scala
test/pages/sections/info/DestinationTypePageSpec.scala

Raising as draft as need to run the JTs and PTs locally. Demoed to Lexi who is happy with the content and logic.
- JT: https://github.com/hmrc/emcs-tfe-journey-tests/pull/513

[ETFE-4293] Added validation for Consignee ERN based on Destination Type

---

app/forms/sections/items/ItemDensityFormProvider.scala
conf/messages
test/forms/sections/items/ItemDensityFormProviderSpec.scala

[ETFE-4310] add validation to item density page which validates input > 0

---

app/config/AppConfig.scala
app/featureswitch/core/config/FeatureSwitchingModule.scala
conf/application.conf
conf/messages
test-utils/fixtures/messages/ConfirmationMessages.scala
test/config/AppConfigSpec.scala

https://github.com/hmrc/emcs-tfe-journey-tests/pull/537
https://github.com/hmrc/app-config-base/pull/10898

[ETFE-4444] update config to remove legacy references, content change

---

app/config/AppConfig.scala
app/connectors/emcsTfe/GetListOfTemplatesHttpParser.scala
app/connectors/emcsTfe/MovementTemplatesConnector.scala
app/controllers/IndexController.scala
app/controllers/actions/predraft/PreDraftAuthActionHelper.scala
app/controllers/sections/templates/UseTemplateController.scala
app/forms/sections/templates/UseTemplateFormProvider.scala
app/models/response/templates/MovementTemplate.scala
app/models/response/templates/MovementTemplates.scala
app/services/MovementTemplatesService.scala
app/views/sections/templates/UseTemplateView.scala.html
conf/app.routes
conf/application.conf
conf/messages
conf/templates.routes
it/connectors/MovementTemplatesConnectorISpec.scala
test-utils/fixtures/BaseFixtures.scala
test-utils/fixtures/TemplateFixtures.scala
test-utils/fixtures/messages/sections/templates/UseTemplateMessages.scala
test/connectors/emcsTfe/GetListOfTemplatesHttpParserSpec.scala
test/controllers/IndexControllerSpec.scala
test/controllers/sections/templates/UseTemplateControllerSpec.scala
test/forms/sections/journeyType/GiveInformationOtherTransportFormProviderSpec.scala
test/forms/sections/templates/UseTemplateFormProviderSpec.scala
test/mocks/connectors/MockMovementTemplatesConnector.scala
test/mocks/services/MockMovementTemplatesService.scala
test/services/MovementTemplatesServiceSpec.scala
test/views/sections/templates/UseTemplateViewSpec.scala

App-Config-Base:
- https://github.com/hmrc/app-config-base/pull/10970

[ETFE-4503] Added new view for UseTemplate question

---

app/assets/stylesheets/application.scss
app/controllers/sections/templates/UpdateTemplateController.scala
app/forms/sections/templates/UpdateTemplateFormProvider.scala
app/models/UserAnswers.scala
app/navigation/InformationNavigator.scala
app/navigation/Navigator.scala
app/viewmodels/checkAnswers/sections/info/InformationCheckAnswersHelper.scala
app/viewmodels/checkAnswers/sections/info/InformationDateOfDispatchSummary.scala
app/viewmodels/checkAnswers/sections/info/InformationInvoiceDateSummary.scala
app/viewmodels/checkAnswers/sections/info/InformationInvoiceReferenceSummary.scala
app/viewmodels/checkAnswers/sections/info/InformationTimeOfDispatchSummary.scala
app/viewmodels/helpers/TagHelper.scala
app/views/sections/templates/UpdateTemplateView.scala.html
conf/messages
conf/templates.routes
test-utils/fixtures/BaseFixtures.scala
test-utils/fixtures/messages/sections/info/DispatchDetailsMessages.scala
test-utils/fixtures/messages/sections/info/InvoiceDetailsMessages.scala
test-utils/fixtures/messages/sections/templates/UpdateTemplateMessages.scala
test/controllers/sections/templates/SaveTemplateControllerSpec.scala
test/controllers/sections/templates/UpdateTemplateControllerSpec.scala
test/forms/sections/templates/UpdateTemplateFormProviderSpec.scala
test/navigation/InformationNavigatorSpec.scala
test/navigation/NavigatorSpec.scala
test/viewmodels/checkAnswers/sections/info/InformationDispatchDateSummarySpec.scala
test/viewmodels/checkAnswers/sections/info/InformationDispatchTimeSummarySpec.scala
test/viewmodels/checkAnswers/sections/info/InformationInvoiceDateSummarySpec.scala
test/viewmodels/checkAnswers/sections/info/InformationInvoiceReferenceSummarySpec.scala
test/views/sections/templates/UpdateTemplateViewSpec.scala

Dependent PR:
- https://github.com/hmrc/emcs-tfe/pull/204

[ETFE-4557] Added UpdateTemplate controller and page, updated routing

---

app/models/UserAnswers.scala
test/models/UserAnswersSpec.scala

JTs PR to go along side this PR - https://github.com/hmrc/emcs-tfe-journey-tests/pull/553

[ETFE-4578] Don't save JourneyType to template

---

app/config/AppConfig.scala
app/views/templates/Layout.scala.html
build.sbt
test/config/AppConfigSpec.scala
test/controllers/ConfirmationControllerSpec.scala

- Includes major version bump to `1` to create `1.0.0` as a demarcation from `beta` -> `live` (to be discussed and agreed with team before merging).

[ETFE-4632] Remove beta banner
